### ISSUE TITLE
GHA: "206-freeze-thaw" shinyjster test failure

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#143]
Run the shinyjster test for the app https://github.com/rstudio/shinycoreci-apps/blob/master/apps/206-freeze-thaw/app.R
The test fails on the last step.

```
> runApp('apps/206-freeze-thaw')

Listening on http://127.0.0.1:6980
shinyjster - Progress: 1/4 (waiting)
shinyjster - Progress: 1/4 (running)
shinyjster - Progress: 2/4 (waiting)
shinyjster - Progress: 3/4 (waiting)
shinyjster - Progress: 3/4 (running)
shinyjster - Progress: 4/4 (waiting)
shinyjster - Progress: 4/4 (running) - Error found: 'Fail' does not equal 'OK'
shinyjster - JS error found! Error:
	msg: 'Fail' does not equal 'OK'
	x: Fail
	y: OK
	xStr: 'Fail'
	yStr: 'OK'
	yStr: 'OK'
```

<img width="1528" alt="206-freeze-thaw-shinyjster-test-failure" src="https://user-images.githubusercontent.com/5369655/118144652-8b2d6480-b3c1-11eb-87b6-b46cebbf7c47.png">

Could this be related to the recent tabset/tabset panel changes?

Note: Reviewing the runTests history, this is build this test started failing from https://github.com/rstudio/shinycoreci-apps/runs/2516442456?check_suite_focus=true

so around 7 days ago, from ~May 5th

**Comment by cpsievert** [comment]
Here's a minimal example

```r
library(shiny)

ui <- fluidPage(
  uiOutput("tabs")
)

server <- function(input, output, session) {
  output$tabs <- renderUI({
    tabsetPanel(
      tabPanel("A", "a"),
      tabPanel("B", "b")
    )
  })
}

shinyApp(ui, server)
```

<img width="118" alt="Screen Shot 2021-05-13 at 12 58 37 PM" src="https://user-images.githubusercontent.com/1365941/118166323-f5a6ca80-b3ea-11eb-8154-461ecddd36e9.png">


The `.active` tab styling doesn't show up because [this renderHook](https://github.com/rstudio/shiny/blob/d65ad5/R/bootstrap.R#L1016-L1026) never gets because `renderUI()` runs through `shiny:::processDeps()` [which uses `doRenderTags()`](https://github.com/rstudio/shiny/blob/d65ad5/R/html-deps.R#L59) (not `renderTags()`)
