### ISSUE TITLE
Linux builds - 016-knitr-pdf shinytest diff viewer takes time to load

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#184]
When running the `shinycoreci::fix_all_gha_branches()`, I ran in to the following issue with all the linux- R builds with `016-knitr-pdf` app

The shinytest diff window wont load for a long time (almost several hours) and during this I could not do any mouse interactions with the IDE/shinytest window.

<img width="1343" alt="Sep_17_shinycoreci-apps_fix_branches" src="https://user-images.githubusercontent.com/5369655/133852610-7b9201e9-fff9-40ee-ab76-9ac48c57f345.png">

Barret mentioned this is due to the .download file differences (esp with Jquery version update) taking a long time to be processed.

@schloerke : Please add more details as you find it relevant. Thank you

**Comment by schloerke** [comment]
It is trying to display a diff of jquery 1.11 to jquery 3.6; Since both of these are on a single line, the text diff is very large. I believe the diff viewer is being overwhelmed and it is taking a __really__ long time to display.

Worked around it by using `shinytest::snapshotUpdate(....)`. Related: https://github.com/rstudio/shinycoreci/pull/80
