### ISSUE TITLE
Github Actions: 202-flexdashboard-kmeans css changes

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci-apps#90]
Ref: https://github.com/rstudio/shinycoreci-apps/runs/1491318073?check_suite_focus=true#step:30:11400

This test has been failing due to some css changes and as result of the left sidebar panel's input widgets being shifted to the top.

Here are Old and New snapshots (and json) of the shinytest results

**OLD:**
<img width="1138" alt="202-flexdashboard-kmeans-old" src="https://user-images.githubusercontent.com/5369655/101086267-796ba980-3565-11eb-8cfb-ebf426f2bd81.png">

**NEW**
<img width="1022" alt="202-flexdashboard-kmeans-new" src="https://user-images.githubusercontent.com/5369655/101086300-84bed500-3565-11eb-854b-957aae5ad2b1.png">

**JSON:**
<img width="1136" alt="202-flexdashboard-kmeans-sample-json-changes" src="https://user-images.githubusercontent.com/5369655/101086329-8ee0d380-3565-11eb-98d7-8c4acdf98245.png">

**DIFFERENCES**
<img width="1109" alt="Dec22-202-flexdashboard-kmeans-differences" src="https://user-images.githubusercontent.com/5369655/102940782-f18f0600-4465-11eb-92b9-8363ce4d2445.png">

**Comment by MadhulikaTanuboddi** [comment]
Carson mentioned this is low priority atm

**Comment by cpsievert** [comment]
Turns out this difference can be isolated to this change in rmarkdown:  https://github.com/rstudio/htmltools/commit/c2335509e378c3402e805382e384139a17bde0b0

Without the change, a missing paragraph (`<p></p>`) used to be present at the top of the sidebar; after this change, the missing paragraph goes away. If we end up doing anything here, it probably makes most sense to add some padding-top to flexdashboard's `.sidebar` CSS
